version: "3"

services:
    postgres:
        container_name: postgres_container
        image: postgres
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
            POSTGRES_DB: easymove
        volumes:
            - postgres:/data/postgres
        ports:
            - 5432:5432
        networks:
            - postgres
        restart: unless-stopped

    pgadmin:
        container_name: pgadmin_container
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: root
            PGADMIN_DEFAULT_PASSWORD: root
        volumes:
            - pgadmin:/root/.pgadmin
        ports:
            - 5050:80
        networks:
            - postgres
        restart: unless-stopped
        depends_on:
            - postgres

networks:
    postgres:
        driver: bridge

volumes:
    postgres:
    pgadmin:
